"""Add storage table with uuid, space, and jsonb payload

Revision ID: 30bd59614c4a
Revises: 001_initial
Create Date: 2026-02-04 23:55:10.343112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30bd59614c4a'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create storage table
    op.create_table('storage',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False, comment='UUID v1 primary key'),
    sa.Column('space', sa.String(length=255), nullable=False, comment='Space identifier for organizing data'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON payload data'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('uuid')
    )
    # Create indexes
    op.create_index('ix_storage_payload', 'storage', ['payload'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_storage_space'), 'storage', ['space'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storage_space'), table_name='storage')
    op.drop_index('ix_storage_payload', table_name='storage', postgresql_using='gin')
    op.drop_table('storage')
    # ### end Alembic commands ###

