"""Add schema_ver field to storage table

Revision ID: 4fed365bf01f
Revises: 30bd59614c4a
Create Date: 2026-02-04 23:58:38.155979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fed365bf01f'
down_revision: Union[str, None] = '30bd59614c4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage', sa.Column('schema_ver', sa.String(length=10), server_default='1', nullable=False, comment='Schema version'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage', 'schema_ver')
    # ### end Alembic commands ###

